-- Seed 4 built-in templates
insert into public.templates (owner_id,is_public,name,description,doc_model)
values (null,true,'名片｜商務聯絡','適合個人/企業名片分享（Bubble）','{"type": "bubble", "title": "名片｜商務聯絡", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Business+Card"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "柯禹彣  |  TapPay", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "Business Development · Payments & LINE solutions", "size": "md", "color": "#333333", "wrap": true}, {"id": "div1", "kind": "divider", "enabled": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "電話", "value": "+886 9xx-xxx-xxx", "action": {"type": "uri", "uri": "tel:+886900000000"}}, {"id": "kv2", "kind": "key_value", "enabled": true, "label": "Email", "value": "you@example.com", "action": {"type": "uri", "uri": "mailto:you@example.com"}}, {"id": "kv3", "kind": "key_value", "enabled": true, "label": "網站", "value": "https://example.com", "action": {"type": "uri", "uri": "https://example.com"}}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "加入 LINE 好友", "action": {"type": "uri", "uri": "https://line.me/R/ti/p/@yourOA"}, "style": "primary", "bgColor": "#0A84FF", "textColor": "#FFFFFF", "autoTextColor": true}]}}'::jsonb)
on conflict do nothing;

insert into public.templates (owner_id,is_public,name,description,doc_model)
values (null,true,'商品促銷｜主視覺+CTA','適合單一商品活動與導購（Bubble）','{"type": "bubble", "title": "商品促銷｜主視覺+CTA", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Promo"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "限時優惠 · eSIM 7 天", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "即買即用，支援多國高速上網。", "size": "md", "color": "#333333", "wrap": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "價格", "value": "NT$ 199 起"}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "立即購買", "action": {"type": "uri", "uri": "https://example.com/buy"}, "style": "primary", "bgColor": "#34C759", "textColor": "#FFFFFF", "autoTextColor": true}]}}'::jsonb)
on conflict do nothing;

insert into public.templates (owner_id,is_public,name,description,doc_model)
values (null,true,'方案比較｜三選一','適合方案比較與導流（Carousel）','{"type": "carousel", "title": "方案比較｜三選一", "cards": [{"id": "cardA", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Plan+A"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "方案 A", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "適合短天數旅行", "size": "md", "color": "#333333", "wrap": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "天數", "value": "3 天"}, {"id": "kv2", "kind": "key_value", "enabled": true, "label": "流量", "value": "1GB"}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "選擇 A", "action": {"type": "uri", "uri": "https://example.com/planA"}, "style": "primary", "bgColor": "#0A84FF", "textColor": "#FFFFFF", "autoTextColor": true}]}}, {"id": "cardB", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Plan+B"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "方案 B", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "最熱門", "size": "md", "color": "#333333", "wrap": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "天數", "value": "7 天"}, {"id": "kv2", "kind": "key_value", "enabled": true, "label": "流量", "value": "3GB"}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "選擇 B", "action": {"type": "uri", "uri": "https://example.com/planB"}, "style": "primary", "bgColor": "#FF9F0A", "textColor": "#FFFFFF", "autoTextColor": true}]}}, {"id": "cardC", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Plan+C"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "方案 C", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "長天數更划算", "size": "md", "color": "#333333", "wrap": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "天數", "value": "15 天"}, {"id": "kv2", "kind": "key_value", "enabled": true, "label": "流量", "value": "10GB"}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "選擇 C", "action": {"type": "uri", "uri": "https://example.com/planC"}, "style": "primary", "bgColor": "#AF52DE", "textColor": "#FFFFFF", "autoTextColor": true}]}}]}'::jsonb)
on conflict do nothing;

insert into public.templates (owner_id,is_public,name,description,doc_model)
values (null,true,'活動行程｜三日版','適合活動/行程資訊分頁（Carousel）','{"type": "carousel", "title": "活動行程｜三日版", "cards": [{"id": "d1", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Day+1"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "Day 1｜集合報到", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "18:00 集合、發放資料", "size": "md", "color": "#333333", "wrap": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "地點", "value": "台北車站"}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "查看地圖", "action": {"type": "uri", "uri": "https://maps.google.com"}, "style": "primary", "bgColor": "#0A84FF", "textColor": "#FFFFFF", "autoTextColor": true}]}}, {"id": "d2", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Day+2"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "Day 2｜主活動", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "09:00 出發，全天行程", "size": "md", "color": "#333333", "wrap": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "提醒", "value": "攜帶證件"}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "行程詳情", "action": {"type": "uri", "uri": "https://example.com/itinerary"}, "style": "primary", "bgColor": "#0A84FF", "textColor": "#FFFFFF", "autoTextColor": true}]}}, {"id": "d3", "section": {"hero": [{"id": "hero_1", "kind": "hero_image", "enabled": true, "image": {"kind": "external", "url": "https://placehold.co/1200x630/png?text=Day+3"}, "ratio": "16:9", "mode": "cover"}], "body": [{"id": "t1", "kind": "title", "enabled": true, "text": "Day 3｜返程解散", "size": "lg", "weight": "bold", "color": "#111111", "align": "start"}, {"id": "p1", "kind": "paragraph", "enabled": true, "text": "12:00 結束，返回集合點", "size": "md", "color": "#333333", "wrap": true}, {"id": "kv1", "kind": "key_value", "enabled": true, "label": "客服", "value": "LINE 聊聊", "action": {"type": "uri", "uri": "https://line.me/R/ti/p/@yourOA"}}], "footer": [{"id": "btn1", "kind": "footer_button", "enabled": true, "label": "聯絡客服", "action": {"type": "uri", "uri": "https://line.me/R/ti/p/@yourOA"}, "style": "primary", "bgColor": "#111111", "textColor": "#FFFFFF", "autoTextColor": true}]}}]}'::jsonb)
on conflict do nothing;
